# Generated by Django 3.2.10 on 2022-08-16 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='econtact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ename',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_enabled',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='module',
            field=models.CharField(max_length=50, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
        migrations.AddField(
            model_name='employee',
            name='setting_id',
            field=models.TextField(default=1, max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='setting_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
