# Generated by Django 3.2.10 on 2022-08-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220816_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='setting_id',
            field=models.TextField(default='', max_length=250),
        ),
    ]
