# Generated by Django 3.2.10 on 2022-08-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_setting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='setting_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
